![imagen](./img/ejercicios.png)

## Ejercicio 1
Importa el módulo de `numpy` y obtén su versión.

In [22]:
import numpy as np

np.version

<module 'numpy.version' from '/Users/carlosoliver/miniconda3/envs/EDA_ENV/lib/python3.10/site-packages/numpy/version.py'>

## Ejercicio 2
Crea un array de una dimensión que vaya de 0 a 9. Llamalo `my_array`

In [30]:
my_array = np.arange(10)
my_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Ejercicio 3
Crea un array 3x3, que sea todo a True

In [31]:
np.full((3,3),True)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

## Ejercicio 4
Extrae todos los impares de `my_array`

In [34]:
mask = (my_array %2 == 1)
my_array[mask]



array([1, 3, 5, 7, 9])

## Ejercicio 5
En un nuevo array, sustituye todos los impares de `my_array` por -1

In [36]:
my_array[mask] = -1
my_array


array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

## Ejercicio 6
En un nuevo array, sustituye todos los impares de `my_array` por -1. Esta vez usa `where`

In [47]:
my_array = np.arange(10)
my_array

# en la funcion where ponerle primero la condicion que buscamos luego que queremos que ponga en esa condicion y por ultimo darle alternativa a eso
my_array = np.where(my_array %2 != 0 ,-1,my_array)


array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

## Ejercicio 7
Convierte `my_array` en un nuevo array de dos dimensiones mediante `reshape`.

In [49]:
#la primera posicion es para indicarle las dimensiones y el segundo la cantidad que queremos meter en cada dimension
my_array = my_array.reshape(2,5)
my_array

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## Ejercicio 8
Concatena los siguientes arrays verticamente

```Python
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
```

In [65]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
np.concatenate([a, b], axis = 0)


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## Ejercicio 9
Concatena los siguientes arrays horizontamente

```Python
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
```

In [77]:
np.concatenate([a, b], axis = 1)


array([[4, 4, 4, 4, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

## Ejercicio 10
Encuentra todos los elementos en común entre ambos arrays. [Para ello usa el método `intersect1d`](https://numpy.org/doc/stable/reference/generated/numpy.intersect1d.html)

```Python
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
```

In [78]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a,b)

array([2, 4])

## Ejercicio 11
Obtén la documentación acerca de la función `concatenate`

In [80]:
np.concatenate??

Call signature:  np.concatenate(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <built-in function concatenate>
Docstring:      
concatenate((a1, a2, ...), axis=0, out=None, dtype=None, casting="same_kind")

Join a sequence of arrays along an existing axis.

Parameters
----------
a1, a2, ... : sequence of array_like
    The arrays must have the same shape, except in the dimension
    corresponding to `axis` (the first, by default).
axis : int, optional
    The axis along which the arrays will be joined.  If axis is None,
    arrays are flattened before use.  Default is 0.
out : ndarray, optional
    If provided, the destination to place the result. The shape must be
    correct, matching that of what concatenate would have returned if no
    out argument were specified.
dtype : str or dtype
    If provided, the destination array will have this dtype. Cannot be
    provided together with `out`.

    .. versionadded:: 1.20.0

casting : {'no', 'equiv', 'safe', 

## Ejercicio 12
Crea un array unidimensional que vaya del 0 al 9. Llámalo `my_array`. 
1. Multiplica cada uno de los elementos de `my_array` por 10, en un nuevo array
2. Accede al primer elemento del array
3. Accede al último elemento del array
4. Imprime por pantalla los numeros del 1 al 7

In [90]:
my_array = np.array([1,2,3,4,5,6,7,8,9])
my_array_multi10 = my_array * 10
my_array[0]
my_array[-1]
my_array[0:7]




array([1, 2, 3, 4, 5, 6, 7])

## Ejercicio 13
Crea un array manualmente de tres filas por tres columnas. Llámalo `my_matrix`

In [93]:
my_matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
my_matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Ejercicio 14
Obtén la siguiente secuencia:

```Python
[ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49]
```

In [95]:
secu = np.arange(1,50,3)
secu

array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49])

## Ejercicio 15
Obtén la siguiente secuencia

```Python
[4., 3.75, 3.5 , 3.25, 3.  , 2.75, 2.5 , 2.25, 2., 1.75, 1.5 ,1.25]
```

In [107]:
secu2 = np.arange(4,1.0,-0.25)
secu2


array([4.  , 3.75, 3.5 , 3.25, 3.  , 2.75, 2.5 , 2.25, 2.  , 1.75, 1.5 ,
       1.25])

In [105]:
np.arange??

Docstring:
arange([start,] stop[, step,], dtype=None, *, like=None)

Return evenly spaced values within a given interval.

``arange`` can be called with a varying number of positional arguments:

* ``arange(stop)``: Values are generated within the half-open interval
  ``[0, stop)`` (in other words, the interval including `start` but
  excluding `stop`).
* ``arange(start, stop)``: Values are generated within the half-open
  interval ``[start, stop)``.
* ``arange(start, stop, step)`` Values are generated within the half-open
  interval ``[start, stop)``, with spacing between values given by
  ``step``.

For integer arguments the function is roughly equivalent to the Python
built-in :py:class:`range`, but returns an ndarray rather than a ``range``
instance.

When using a non-integer step, such as 0.1, it is often better to use
`numpy.linspace`.

See the Warning sections below for more information.

Parameters
----------
start : integer or real, optional
    Start of interval.  The interva

## Ejercicio 16
Lee la imagen "numpy.png"

![imagen](./img/numpy.png)

In [110]:
import matplotlib.pyplot as plt


In [114]:
imagen = plt.imread("./img/numpy.png")
np.ndim(imagen)
np.shape(imagen)
np.size(imagen)

936360

## Ejercicio 17
Crea un array de 4x1. A continuación convierte el array a un 2x2

In [117]:
nue_array =np.array([[1],[2],[3],[4]])
nue_array.reshape(2,2)

array([[1, 2],
       [3, 4]])

## Ejercicio 18
Crea una secuencia aleatoria. La secuencia se tiene que componer de 4 matrices de 5x3. Serían 3 dimensiones diferentes.

In [118]:
import random

In [139]:
np.random.rand(5,3)

array([[0.13500749, 0.19187451, 0.61072525],
       [0.71032737, 0.82272924, 0.21154349],
       [0.71225842, 0.55514616, 0.54948117],
       [0.87549909, 0.19656358, 0.21232965],
       [0.18259482, 0.71217966, 0.96400646]])

## Ejercicio 19
Crea una matriz de 10x1, toda ella compuesta por `False`. Después transformalo en un 2x5

In [143]:
array19 = np.full((10,1),False)

In [146]:
np.reshape(array19,(2,5))

array([[False, False, False, False, False],
       [False, False, False, False, False]])

In [145]:
np.reshape??

Signature:       np.reshape(a, newshape, order='C')
Call signature:  np.reshape(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function reshape at 0x11083ac20>
File:            ~/miniconda3/envs/EDA_ENV/lib/python3.10/site-packages/numpy/core/fromnumeric.py
Source:         
@array_function_dispatch(_reshape_dispatcher)
def reshape(a, newshape, order='C'):
    """
    Gives a new shape to an array without changing its data.

    Parameters
    ----------
    a : array_like
        Array to be reshaped.
    newshape : int or tuple of ints
        The new shape should be compatible with the original shape. If
        an integer, then the result will be a 1-D array of that length.
        One shape dimension can be -1. In this case, the value is
        inferred from the length of the array and remaining dimensions.
    order : {'C', 'F', 'A'}, optional
        Read the elements of `a` using this index order, and place the
        elements into the reshaped ar

## Ejercicio 20
Dado el siguiente array

```Python
x =np.random.randint(10, 20, size = (5,2,6))
```

1. ¿Cuántos elementos tiene el array?
2. ¿Cuántas dimensiones?
3. ¿Cuántos elementos tiene cada dimensión?

In [148]:
x =np.random.randint(10, 20, size = (5,2,6))
x

array([[[19, 13, 13, 19, 13, 10],
        [19, 11, 18, 19, 19, 19]],

       [[18, 19, 11, 10, 17, 15],
        [17, 18, 18, 11, 17, 10]],

       [[12, 16, 10, 11, 15, 14],
        [17, 19, 12, 13, 12, 15]],

       [[16, 16, 14, 14, 18, 19],
        [16, 18, 16, 14, 17, 13]],

       [[12, 17, 18, 19, 17, 14],
        [11, 12, 10, 12, 12, 18]]])

In [ ]:
#60 elementos

#3 dimensiones
#5x2x6 elementos