![imagen](./img/ejercicios.png)

## Ejercicio 1
1. Crea un array que vaya del 0 al 9 y que se llame `my_array`
2. Imprime por pantalla los elementos [9 7 5 3 1] en ese orden.

In [4]:
import numpy as np

In [5]:
my_array = np.arange(0,10)


In [6]:
my_array[9::-2]

array([9, 7, 5, 3, 1])

## Ejercicio 2
Imprime por pantalla la secuencia [8 7] del array `my_array`

In [7]:
my_array[8:6:-1]

array([8, 7])

## Ejercicio 3
Imprime por pantalla la secuencia [2 1 0] de `my_array`

In [8]:
my_array[2::-1]

array([2, 1, 0])

## Ejercicio 4
1. Crea una matriz de 4x5, con una secuencia del 1 al 20
2. Invierte totalmente la matriz. Tanto las filas, como las columnas

In [9]:
array2 = np.arange(1,21)
array2 = np.reshape(array2, [4,5])
array3 = np.flip(array2)
array3

array([[20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])

In [10]:
np.reshape??

Signature:       np.reshape(a, newshape, order='C')
Call signature:  np.reshape(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function reshape at 0x10b861bd0>
File:            ~/miniconda3/envs/EDA_ENV/lib/python3.10/site-packages/numpy/core/fromnumeric.py
Source:         
@array_function_dispatch(_reshape_dispatcher)
def reshape(a, newshape, order='C'):
    """
    Gives a new shape to an array without changing its data.

    Parameters
    ----------
    a : array_like
        Array to be reshaped.
    newshape : int or tuple of ints
        The new shape should be compatible with the original shape. If
        an integer, then the result will be a 1-D array of that length.
        One shape dimension can be -1. In this case, the value is
        inferred from the length of the array and remaining dimensions.
    order : {'C', 'F', 'A'}, optional
        Read the elements of `a` using this index order, and place the
        elements into the reshaped ar

## Ejercicio 5

Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[1, 2],
       [6, 7]])
```

In [11]:
array2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

## Ejercicio 6
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 1,  3,  5],
       [11, 13, 15]])
```

In [12]:
array2[:3:2,::2]

array([[ 1,  3,  5],
       [11, 13, 15]])

## Ejercicio 7
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])
```

In [13]:
array2[:3:,::-1]

array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])

## Ejercicio 8
Dado el siguiente array:

```Python
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
```

Filtra el array para quedarte únicamente con los loros.

Resuélvelo de dos maneras diferentes

In [14]:
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])


In [15]:
x[(x == "Loro")]


array(['Loro', 'Loro'], dtype='<U5')

## Ejercicio 9
Crea una secuencia de 20 elementos y transformala en un array compuesto por 2 matrices de 5x2

In [16]:
nueva_array = np.arange(0,20)
nueva_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [17]:
np.reshape(nueva_array,(5,-1))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

## Ejercicio 10
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])
```

In [18]:
array10 = array2.copy()

In [19]:
array10[::-1,::-1]

array([[20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])

## Ejercicio 11
Crea un array de 10 0s. ¿Cuánto ocupa en memoria?

Sustituye el 4to elemento por 1, e imprime el array por pantalla

In [20]:
array11 = np.full((0,10),0)
np.nbytes[array11]

8

## Ejercicio 12
Crea un vector que vaya del 10 al 49

Inviértelo

In [21]:
array12 = np.arange(10,50)
array12[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

## Ejericio 13
Encuentra los indices de los valores que no sean 0 del siguiente vector [1,2,0,0,4,0]. El output sería [0, 1, 4]. [Encuentra el método apropiado en la documentación.](https://numpy.org/doc/)

In [22]:
vector = [1,2,0,0,4,0]

In [23]:
np.nonzero(vector)

(array([0, 1, 4]),)

## Ejercicio 14
Crea una matriz de numeros aleatorios 10x10. Encuentra los valores mínimo y máximo.

In [24]:
import random

In [25]:
np.random.rand(10,10)

array([[6.51247475e-01, 6.09186346e-01, 3.13385696e-01, 9.31608526e-01,
        7.84745933e-01, 1.93786257e-01, 1.61265899e-01, 1.55944561e-01,
        3.06420659e-01, 1.13353502e-01],
       [4.98921373e-01, 4.81843170e-01, 4.58618865e-01, 8.14118688e-01,
        7.65893516e-01, 6.02856973e-01, 8.40831199e-01, 3.85219886e-01,
        1.14854078e-01, 2.84802659e-01],
       [9.87407322e-01, 1.83097951e-01, 9.50661420e-01, 7.41878457e-04,
        8.57704658e-01, 3.09658749e-01, 7.24945488e-01, 8.29115567e-02,
        4.39682999e-01, 9.69270280e-01],
       [3.10663879e-02, 2.50096729e-01, 9.45656783e-01, 4.62858329e-01,
        8.60313255e-02, 7.46287594e-01, 5.49675919e-01, 8.68795796e-01,
        8.48627032e-02, 8.64203236e-01],
       [5.29669274e-01, 1.35624862e-01, 8.34516733e-01, 5.13357822e-01,
        1.34613916e-01, 1.35011673e-01, 2.60169589e-01, 4.65197037e-01,
        1.54309229e-01, 4.93484909e-01],
       [1.85383518e-01, 7.89701015e-01, 1.14310259e-01, 8.79073197e-01,
   

## Ejercicio 15
Crea un vector aleatorio de tamaño 30 y calcula su media

In [26]:
array_15 = np.arange(0,30)

In [27]:
np.mean(array_15)

14.5

## Ejercicio 16
Crea un array cuadrado de 2D, con las dimensiones que quiras, pero que todo el borde esté compuesto por 1s, y el interior por 0s

In [28]:
array16 = np.ones((10,10))
array16[0:1:] = 0
array16[::,0:1:]=0
array16[::,9::] = 0
array16[9::,::] = 0
array16



array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [29]:
np.full??

Signature: np.full(shape, fill_value, dtype=None, order='C', *, like=None)
Docstring:
Return a new array of given shape and type, filled with `fill_value`.

Parameters
----------
shape : int or sequence of ints
    Shape of the new array, e.g., ``(2, 3)`` or ``2``.
fill_value : scalar or array_like
    Fill value.
dtype : data-type, optional
    The desired data-type for the array  The default, None, means
     ``np.array(fill_value).dtype``.
order : {'C', 'F'}, optional
    Whether to store multidimensional data in C- or Fortran-contiguous
    (row- or column-wise) order in memory.
like : array_like, optional
    Reference object to allow the creation of arrays which are not
    NumPy arrays. If an array-like passed in as ``like`` supports
    the ``__array_function__`` protocol, the result will be defined
    by it. In this case, it ensures the creation of an array object
    compatible with that passed in via this argument.

    .. versionadded:: 1.20.0

Returns
-------
out : ndarra

## Ejercicio 17
Crea una mtriz de 8x8, y rellénala con 0s y 1s. Tienes que replicar:
```Python
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
```

In [61]:
array17 = np.ones((8,8))
array17 = (np.indices((8, 8)).sum(axis=0) % 2)


array17

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

## Ejercicio 18
Replica la matriz del apartado anterior, pero en este caso usando [la función `tile`](https://numpy.org/doc/stable/reference/generated/numpy.tile.html)

In [74]:
array18 = np.array([[0,1],
                   [1,0]])

#la funcion tile repite la matriz en horizontal y vertical
np.tile(array18,(4,4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [72]:
array18

array([[0, 1],
       [1, 0]])

## Ejercicio 19
Crea una matriz aleatoria de 5x5 y normaliza sus valores. Para normalizar tienes que restar sus valores por la media(`np.mean`) y dividir el resultado por la desviación estándar(`np.std`).

In [87]:
array_19 = np.random.randint(0,10,(5,5))

In [88]:
array_19 = (array_19 - np.mean(array_19))

In [89]:
print(array_19/ np.std(array_19))

[[ 1.42555777 -1.31589948 -1.31589948  1.12095141  0.51173869]
 [-1.31589948  0.51173869 -1.01129312 -0.4020804   1.12095141]
 [ 0.20713233 -1.31589948  0.81634505  1.42555777  0.20713233]
 [ 0.51173869 -0.09747404 -0.70668676 -1.01129312  0.51173869]
 [-1.31589948  1.42555777 -1.01129312 -0.4020804   1.42555777]]


## Ejercicio 20
1. Crea una secuencia de números que vayan del 0 al 10.
2. Crea un nuevo array, que parta del anterior, pero sustituya por el valor -1, todos los elementos cuyo valor se encuentre entre el 3 y el 8.
3. Crea un nuevo array que niegue todos los elementos entre el 3 y el 8

In [90]:
array_20 = np.arange(1,11)

In [92]:
array_20_1 = np.copy(array_20)

In [96]:
array_20_1[2:9] = -1
array_20_1

array([ 1,  2, -1, -1, -1, -1, -1, -1, -1, 10])

In [100]:
array_20_2 = np.arange(1,11)
#asterisco antes del igual convierte al elemento en negativo
array_20_2[2:9] *= -1
array_20_2


array([ 1,  2, -3, -4, -5, -6, -7, -8, -9, 10])

## Ejercicio 21
#### Bonus track. Mini hundir la flota
1. Crea un tablero de 10x10 relleno del carácter espacio ( ).
2. Posiciona un par de barcos en [(0,1), (1,1)] y [(1,3), (1,4), (1,5), (1,6)]. Los barcos serán Os mayúsculas. Como ves, un barco de dos posiciones de eslora y otro de cuatro.
3. Recibe un disparo en uno de los barcos, sustituyendo la O por una X
4. Recibe un disparo en agua, sustituyendo uno de los espacios por un guión: -
5. Ignorando los disparos recibidos, ahora prueba a posicionar otro barco de 4 posiciones dentro del tablero, pero **de manera ALEATORIA.**

**TIP apartado 5**: El barco tendrá una posición inicial aleatoria dentro del tablero, y una orientación también aleatoria (N,S,E,O).

Por ejemplo, si tu posicion inicial fuese (5,0) y la orientación O, no podrias ponerlo porque se sale del tablero. Ahora bien, si fuese orientación este, si podrías, y ocuparía las posiciones [(5,0), (5,1), (5,2), (5,3)]. Por tanto tendrás que iterar con un bucle si es posible encajar el barco en el tablero, y el bucle terminará cuando lo consigas encajar. **Ojo con las posiciones donde ya hay barco!!!**

Usa `import random` para elegir las coordenadas aleatorias.